[[group]]
name = "auth"
group = "api"

[[group]]
name = "authPublic"
group = "apiPublic"

[[route]]
group = "authPublic"
method = "POST"
httpPath = "/login"
handlers = ["jump.Login"]

[[route]]
group = "auth"
method = "GET"
httpPath = "/logout"
handlers = ["jump.Logout"]

[[route]]
group = "auth"
method = "POST"
httpPath = "/logout"
handlers = ["jump.Logout"]
