[[group]]
name = "proxy"
group = "api"
httpPath = "/proxy"
handlers = ["proxy.CheckPermissionsMW"]

[[route]]
method = "GET"
group = "proxy"
httpPath = "/file/:prefix/:filename"
handlers = ["proxy.Get"]

[[route]]
method = "GET"
group = "proxy"
httpPath = "/next/:prefix/:filename"
handlers = ["proxy.GetNext"]

[[route]]
method = "POST"
group = "proxy"
httpPath = "/:prefix/:filename"
handlers = ["proxy.Export"]
